import { serve } from '@hono/node-server';
import { Hono } from 'hono';
import { cors } from 'hono/cors';
import 'dotenv/config';
import { HTTPException } from 'hono/http-exception';
import type { ContentfulStatusCode } from 'hono/utils/http-status';
import busStops from './data/bus_stops.json' with { type: 'json' };
import { cleanData, getDistance } from './utils.js';
import type { BusStopTimings, BusTimingResponse } from './types.js';

const app = new Hono().basePath('/api');

app.use('*', cors({ origin: process.env.FRONTEND_URL }));

app.get('/bus-timings', async (c) => {
  const url: string =
    'https://datamall2.mytransport.sg/ltaodataservice/v3/BusArrival';
  const { busStopCode } = c.req.query();

  try {
    const response = await fetch(url + `?BusStopCode=${busStopCode}`, {
      headers: { AccountKey: process.env.DATAMALL_API_KEY! },
    });
    const status = response.status as ContentfulStatusCode;

    if (!response.ok) {
      console.error(response.status, 'Error fetching bus timing');
      const errorResponse = new Response('Error fetching bus timings');
      throw new HTTPException(status, { res: errorResponse });
    }

    const data: BusTimingResponse = await response.json();
    const cleanedData: BusStopTimings = cleanData(data, busStops);
    return c.json(cleanedData);
  } catch (error) {
    console.error('Error fetching bus timings: ', error);
    const errorResponse = new Response('LTA bus timing error');
    throw new HTTPException(502, { res: errorResponse });
  }
});

app.get('/nearest-bus-stop', async (c) => {
  const { latitude, longitude } = c.req.query();

  let nearestBusStopCode = null;
  let nearestBusStopDistance = null;

  for (const busStop of busStops) {
    const busStopLat = busStop.Latitude;
    const busStopLon = busStop.Longitude;

    const distance = getDistance(
      parseFloat(latitude),
      parseFloat(longitude),
      busStopLat,
      busStopLon,
    );

    if (nearestBusStopDistance == null || distance < nearestBusStopDistance) {
      nearestBusStopCode = busStop.BusStopCode;
      nearestBusStopDistance = distance;
    }
  }

  return c.json({
    nearestBusStopCode: nearestBusStopCode,
  });
});

app.get('/:busStopCode/services', async (c) => {
  const busStopCode = c.req.param('busStopCode');

  const busStop = busStops.find((stop) => stop.BusStopCode == busStopCode);

  if (!busStop) {
    console.error('Bus stop is non-existent');
    const errorResponse = new Response('Bus stop is non-existent');
    throw new HTTPException(404, { res: errorResponse });
  }

  return c.json({
    busStopName: busStop.Description,
    busStopCode: busStop.BusStopCode,
    serviceNos: busStop.ServiceNos,
  });
});

// app.onError((err, c) => {
//   if (err instanceof HTTPException) {
//     // Return the error response generated by HTTPException
//     return err.getResponse()
//   }
//   // For any other unexpected errors, log and return a generic 500 response
//   console.error(err)
//   return c.text('Internal Server Error', 500)
// })

serve(
  {
    fetch: app.fetch,
    port: 3000,
  },
  (info) => {
    console.log(`Server is running on http://localhost:${info.port}`);
  },
);
