import { serve } from '@hono/node-server'
import { Hono } from 'hono'
import { cors } from 'hono/cors'
import 'dotenv/config'
import { HTTPException } from 'hono/http-exception'
import type { ContentfulStatusCode } from 'hono/utils/http-status'

const app = new Hono().basePath('/api')

app.use('*', cors({ origin: process.env.FRONTEND_URL}))

app.get('/bus-timings', async (c) => {
  const url: string = "https://datamall2.mytransport.sg/ltaodataservice/v3/BusArrival";
  const busStopCode: number = 83139;

  try {
    const response = await fetch(url + `?BusStopCode=${busStopCode}`,
      { headers : { "AccountKey": process.env.DATAMALL_API_KEY! }}
    );
    const status = response.status as ContentfulStatusCode;

    if (!response.ok) {
      console.error(response.status, "Error fetching bus timing");
      const errorResponse = new Response("Error fetching bus timings")
      throw new HTTPException(status, { res: errorResponse });
    }

    const data = await response.json();
    return c.json(data);

  } catch (error) {
      console.error("Error fetching bus timings: ", error);
      const errorResponse = new Response("LTA bus timing error");
      throw new HTTPException(502, { res: errorResponse});
  }
})

// app.onError((err, c) => {
//   if (err instanceof HTTPException) {
//     // Return the error response generated by HTTPException
//     return err.getResponse()
//   }
//   // For any other unexpected errors, log and return a generic 500 response
//   console.error(err)
//   return c.text('Internal Server Error', 500)
// })


serve({
  fetch: app.fetch,
  port: 3000
}, (info) => {
  console.log(`Server is running on http://localhost:${info.port}`)
})
